# Generated by Django 5.2.7 on 2025-11-07 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(db_index=True, max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_album_id', models.CharField(db_index=True, max_length=255)),
                ('ordered_ids', models.JSONField()),
                ('comparisons', models.JSONField(blank=True, default=list)),
                ('comparisons_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rankings', to='myapp.savedalbum')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='savedalbum',
            index=models.Index(fields=['user', 'album_id'], name='myapp_saved_user_id_eaaadd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedalbum',
            unique_together={('user', 'album_id')},
        ),
        migrations.AddIndex(
            model_name='albumranking',
            index=models.Index(fields=['spotify_album_id', 'user', 'created_at'], name='myapp_album_spotify_ef2ed8_idx'),
        ),
    ]
